### ISSUE TITLE
Error running Colab notebook - 5th block of code

### ISSUE THREAD

**Issue by WhiteD3vil** [SurajDonthi/Multi-Camera-Person-Re-Identification#10]
Generating Spatial-Temporal Distribution.

Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to /root/.cache/torch/hub/checkpoints/resnet50-19c8e357.pth
100%
97.8M/97.8M [00:15<00:00, 6.82MB/s]

GPU available: True, used: True
TPU available: False, using: 0 TPU cores
CUDA_VISIBLE_DEVICES: [0]
Using native 16bit precision.

  | Name        | Type            | Params
------------------------------------------------
0 | model       | Sequential      | 23 M  
1 | dropout     | Dropout         | 0     
2 | classifier0 | ClassifierBlock | 718 K 
3 | classifier1 | ClassifierBlock | 718 K 
4 | classifier2 | ClassifierBlock | 718 K 
5 | classifier3 | ClassifierBlock | 718 K 
6 | classifier4 | ClassifierBlock | 718 K 
7 | classifier5 | ClassifierBlock | 718 K 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-2155156718ea> in <module>()
     26 
     27 #
---> 28 trainer.fit(model, data_module)
     29 
     30 # Testing the loss & accuracy of the model

8 frames
/content/MTMCT-Person-Re-Identification/mtmct_reid/data.py in val_dataloader(self)
    214 
    215     def val_dataloader(self):
--> 216         test_loader = DataLoader(self.test, batch_size=self.test_batchsize,
    217                                  shuffle=False, num_workers=self.num_workers,
    218                                  pin_memory=True)

AttributeError: 'ReIDDataModule' object has no attribute 'test'

**Comment by hive1506** [comment]
Import `random_split`


![image](https://user-images.githubusercontent.com/67891541/104482432-ef474400-55ec-11eb-938c-268533d095f1.png)

And then 

![image](https://user-images.githubusercontent.com/67891541/104483597-4d285b80-55ee-11eb-8cb0-fb77db1dcaaa.png)


Now, try again

maybe this will help

**Comment by WhiteD3vil** [comment]
Tried the above but getting the same error "AttributeError: 'ReIDDataModule' object has no attribute 'test' "
