### ISSUE TITLE
How to query?

### ISSUE THREAD

**Issue by ankurguria** [SurajDonthi/Multi-Camera-Person-Re-Identification#18]
Could you share the code to query on a single image?
I cannot understand how exactly the data is being fed into the model.

**Comment by ankurguria** [comment]
@SurajDonthi where exactly is the output of the testing stored?

**Comment by SurajDonthi** [comment]
@ankurguria you'll need 2 attributes as input:
1. Image/Frame
2. Timestamp formatted in either Market-1501 or Duke MTMC format.
You can create a Dataset from this.

```python
# INPUTS
query_image: torch.Tensor()
query_cam_id: torch.Tensor()
query_frame: torch.Tensor()

class Dataset(...):
    def __init__(self, ...):
    ...
    self.gallery_images: torch.Tensor()
    self.labels: torch.Tensor()
    self.gallery_cam_ids: torch.Tensor()
    self.gallery_frames: torch.Tensor()
    ...
    
    def __getitem__(self, idx):
    # Preprocessing
    ...
    return processed_gallery_img[idx], self.gallery_cam_ids[idx], self.gallery_frames[idx]

dataset = Dataset(...)
dataloader(dataset, shuffle=False, ...)
```

To query on a single image against a gallery, 
1. You'll need to first compute the feature vectors `self(x, training=False)` of all gallery images (pass through CNN) & also collect their respective `cam_id` & `frame`/`timestamp`.

```python
# Compute Feature Vector of Query Image
query_feature = self(query)

# Compute Feature Vector of all Gallery Images
gallery_features = torch.Tensor()
gallery_cam_ids = torch.Tensor()
gallery_frames = torch.Tensor()

for gallery_image, cam_id, frame in dataloader:
    feature_sum = self(gallery_image, training=False)
    flipped_image = fliplr(gallery_image)
    feature_sum += self(flipped_image, training=False)

    gallery_features = torch.cat([gallery_features, feature_sum])
    gallery_cam_ids = torch.cat([gallery_cam_ids, cam_id])
    gallery_frames = torch.cat([gallery_frames, frame])
```

2. With these two attributes for both your query image & all the gallery images, you can calculate the `joint_scores()` given the Spatio-Temporal Distribution.

```python
scores = joint_scores(query_feature, query_cam_id, query_frame, gallery_features, gallery_cam_ids, gallery_frames, spatio_tempotal_distribution)

# Optional
reranked_scores = re_ranking(scores)
```

3. So the one with the highest joint score is the predicted gallery image/person_id.

```python
gallery_image_idx = np.argmax()
person_id = dataset.labels[gallery_image_idx]
```

Note: Functions to compute Spatio-Temporal Distribution(`smooth_st_distribution`), Joint Score(`joint_score`) & Re-ranking(re_ranking) are available in `metrics.py`.

I hope this detailed explanation is helpful.

**Comment by SurajDonthi** [comment]
> @SurajDonthi where exactly is the output of the testing stored?

Currently, only the metrics are stored. However, feel free to create a pull request to add storage of the test outputs.

**Comment by ankurguria** [comment]
@SurajDonthi thanks a lot for the detailed explanation. I understood the code.

I did try running this on Kaggle notebooks using the demo.ipynb. There are some output visualizations when I "commit and save it" on Kaggle. There must be some code already in the repo doing the visualization. But I wasn't able to find them. Could you please help me in pointing that chunk of code?

**Comment by SurajDonthi** [comment]
@ankurguria, what you are looking for is `engine.py`. The answer to all your questions lie in this file.

With regard to visualization, I think you're referring to the Spatio-Temporal Distribution. You can find it here: https://github.com/SurajDonthi/Multi-Camera-Person-Re-Identification/blob/6ebf48f44616c3c750670a3afc3b20d99b659ce1/mtmct_reid/engine.py#L200. 

Please feel free to contribute any additional visualizations.
