### ISSUE TITLE
When i tried to run using colab: Error: 'Path 'data/raw/Market-1501-v15.09.15' does not exist!

### ISSUE THREAD

**Issue by WhiteD3vil** [SurajDonthi/Multi-Camera-Person-Re-Identification#6]
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-32-d66e03368717> in <module>()
     16                                     )
     17 
---> 18 data_module = ReIDDataModule.from_argparse_args(args)
     19 
     20 model = ST_ReID(data_module.num_classes, learning_rate=args.learning_rate,

2 frames
/content/MTMCT-Person-Re-Identification/mtmct_reid/data.py in __init__(self, data_dir, st_distribution, train_subdir, test_subdir, query_subdir, train_batchsize, val_batchsize, test_batchsize, num_workers, random_erasing, color_jitter, save_distribution)
    114         if not self.data_dir.exists():
    115             raise Exception(
--> 116                 f"'Path '{self.data_dir.__str__()}' does not exist!")
    117         if not self.data_dir.is_dir():
    118             raise Exception(

Exception: 'Path 'data/raw/Market-1501-v15.09.15' does not exist!

**Comment by SurajDonthi** [comment]
You need to run the first cell!

![Code Cell](https://imgur.com/xl6r0Sp)

![Code Cell 2](https://imgur.com/9DcdY81)
